### ISSUE TITLE
每日任务

### ISSUE THREAD

**Issue by hx-code** [hx-code/study#1]

**Comment by hx-code** [comment]
https://leetcode-cn.com/classic/problems/binary-tree-preorder-traversal/description/
第144题二叉树前序v遍历

**Comment by qq782874135** [comment]
![1651110881(1)](https://user-images.githubusercontent.com/28087779/165661023-fa1e2fa2-ca74-4e43-9ddb-49babbe88818.png)

**Comment by lxchuan12** [comment]
> ![1651110881(1)](https://user-images.githubusercontent.com/28087779/165661023-fa1e2fa2-ca74-4e43-9ddb-49babbe88818.png)

面试官：递归有些简单，能试试迭代方法吗~

**Comment by masterX89** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/8510146/165666371-bd5ba555-1a8e-4ee6-b32c-b17e1c333bd5.png">

js 的迭代来咯，js 写法里 Array.prototype.pop() 是会返回 top 的，而 c++ 的迭代写法里要先拿到 top，然后执行 stack 的 pop

我每日一题的仓库：[new-leetcode](https://github.com/masterX89/new-leetcode)

**Comment by hx-code** [comment]
![屏幕截图 2022-04-28 133809](https://user-images.githubusercontent.com/71773836/165683878-e9f007ae-7701-4802-bfdb-eb1130121b6f.jpg)

**Comment by lwindh** [comment]
![image](https://user-images.githubusercontent.com/42671309/165749778-24e84c8f-b4e8-44bd-bed8-a1cefa8bd4d1.png)

**Comment by qqzhangyanhua** [comment]
![1651193688(1)](https://user-images.githubusercontent.com/47852997/165870161-44a8bcad-498f-4c0a-a68c-b721c35b45f8.jpg)
先把zij自己昨天的任务完成，等会参考下大家的写法研究一下。
